version: '3.8'

services:

  postgres:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: taskmanagement
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d taskmanagement"]
      interval: 15s
      timeout: 5s
      retries: 3